#!/bin/sh

if [[ $1 == upgrade ]]; then
    /bin/launchctl unload /Library/LaunchDaemons/com.simpzan.listport.plist
fi

if [[ $1 == install || $1 == upgrade ]]; then
    chown 0:0 /Library/LaunchDaemons/com.simpzan.listport.plist
    chown 0:0 /usr/bin/listport
    /bin/launchctl load /Library/LaunchDaemons/com.simpzan.listport.plist
fi

exit 0
